name: Valid JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_review:
    types: [submitted]

env:
  SWIFT_IMAGE: swiftlang/swift@sha256:5765a1bd4c7ff05e35a1095598a70bcaf6a5a8e3e8fc48141e5cb0307a295852  # swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-09-a
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate JSON
        run: docker run --rm --env GITHUB_TOKEN=$GITHUB_TOKEN -v "$PWD:/host" -w /host $SWIFT_IMAGE swift validate.swift
